# Site
repository: Rocknpools/Rocknpools.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Paolo Squadrito
title: Antenna Engineer
email: paolosquadrito89@gmail.com
canonicalurl: https://rocknpools.github.io
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: jekyllrb
github_username:  rocknpools
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: paolosquadrito
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
orcid_username: 0000-0002-3115-020X


# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/IMG_1442.jpg
about_content: | # this will include new lines to allow paragraphs

  **Nationality:** Italian

  **Location:** Aalborg (Denmark)

  **Languages:** italian (native speaker), english (fluent), french (basic)

  **Summary:**
  Hi, my name is Paolo and I’m a telecommunication engineer passionate about antennas and space.  I am most skilled in <mark>Antenna Design for Small Satellite terminal</mark>, additionally, I'm also an IT enthusiast which enjoy the wonderful world of coding.  I have previous experience working in a team in several academic/corporate environments.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Skills section
skills: |
  **Main skills:**
    - Microwave Engineering
    - Antennas Array
    - Antennas for Small Satellite Terminal
    - Printed Circuit Board (PCB) Design
    - Antenna Measurements

  **Design Software:**
  - CST
  - HFSS
  - Altium Designer

  **Programming Languages:**
  - Python
  - Matlab
  - C
  - Java


# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  As well as Antennas and IT, I also enjoy doing the following:
   - Following technology developments
   - Games
   - Reading
   - Building things, particularly with LEGO
   - Coding

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
